### ISSUE TITLE
Upload stuck at 0 bytes

### ISSUE THREAD

**Issue by jesusgp22** [rico345100/socket.io-file#7] opened 2017-09-13 19:37 UTC
Hi, I am getting an issue where uploading start but it doesn't move from 0 bytes, here is what the console is printing:

On the front-end:
```
Start uploading {name: "aerial.mp4", size: 928498, uploadTo: ""}
 Streaming... sent 0 bytes.
```

On the backend:
```
Start uploading { name: 'aerial.mp4',
  size: 928498,
  uploadDir: 'C:\\Users\\jesus\\workspace\\projections.io\\socket-server\\temp\\aerial.mp4' }
0 / 928498 byte(s)
0 / 928498 byte(s)
0 / 928498 byte(s)
0 / 928498 byte(s)
0 / 928498 byte(s)
0 / 928498 byte(s)
```

My settings (everything is copy pasted from the example):

    const uploader = new SocketIOFile(socket, {
        uploadDir: TEMP_DIR,
        accepts:['videp/mp4'],
        maxFileSize: 4194304,
        chunkSize: 10240,
        transmissionDelay: 0,
        overwrite: true
    });

My package json:

```
{
  "name": "socket-server",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "node index.js",
    "dev": "nodemon"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "express": "^4.15.4",
    "firebase-admin": "^5.2.1",
    "socket.io": "^2.0.3",
    "socket.io-file": "^2.0.12",
    "socket.io-file-client": "^2.0.12",
    "uuid": "^3.1.0"
  }
}

```

Any thoughts?

**Comment by rico345100** [comment] 2017-09-14 01:24
I just tested to make everything new from example codes and it works. I need more detail information to help your issue.

Could you tell me which browser and node version you were used and did you upload the file after ready event fired?

This issue was exists serveral months ago, might be duplicate of this: https://github.com/rico345100/socket.io-file/issues/3

**Comment by jesusgp22** [comment] 2017-09-14 13:53
You are right, this was a duplicate of that issue, it is important to notice that the server code has to run before the client can init an uploader instance, btw is there any way to send files to a client with this module? Thank you!

**Comment by rico345100** [comment] 2017-09-14 14:18
@jesusgp22 You mean that sending file from server to client? This module was designed for uploading binary data(like file) to remote server, not download from it.

**Comment by jesusgp22** [comment] 2017-09-14 14:19
@rico345100 I figured so, thank you for such a quick response.

**Comment by rico345100** [comment] 2017-09-14 16:14
@jesusgp22 No problem. Looks like I can close this now. If you have any question related about this, feel free to re-open this issue.

Oh, If you like this module, don't forget to give me a star :)

**Closed as completed by rico345100** 2017-09-14 16:14 UTC
